mode: auto

avatar:
  url: /images/jinshi.jpg
  status:
    enable: true
    emoji: ✨
    message: Twinkle, twinkle, little star.

# UI
banner:
  enable: true
  title: 南城的小站
  border: false
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# Background_image
bg_image:
  enable: true
  url: /images/light_bg.png # recomend image related to your mode
  dark: /images/dark_bg_1.jpg
  # blur: 30px
  opacity: 1

# Siderbar
sidebar:
  # bg_image: /images/siderbar_img.jpg
  # dark_bg_image: /images/siderbar_img.jpg
  bg_position: bottom 1rem center
  tagcloud:
    enable: true
    amount: 20

# Favicon
favicon: /images/icon.png

# CDN
cdn:
  pre: ""
  css:
    yun-markdown-css: "yun_markdown_css"
    prism-theme-vars: "prism_theme_vars"
  js:
    base:
    async:
    defer:

fireworks:
  enable: false
  colors:
  - "102, 167, 221"
  - "62, 131, 225"
  - "33, 78, 194"
  # - "3, 28, 95"
  # - "0, 8, 55"

medium_zoom: true

reward:
  enable: false
  comment: 我很可爱，请给我钱
  methods:
    - name: 支付宝
      path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ 支付
      path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: 微信支付
      path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      color: '#2DC100'
      icon: ri:wechat-pay-line

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - 欢迎参与讨论，亦可前往 <a href="https://github.com/NanCheng112" target="_blank">GitHub</a> 与我交流。

waline:
  enable: true
  serverURL: https://nan-cheng112-github-27g61sqqs-nanchengs-projects-9e1ea92d.vercel.app/
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bmoji/
  locale:
    placeholder: 留下宝贵的意见~
  requiredMeta: [nick]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

footer:
  since: 2025
  # icon:
  #   url: https://sponsors.yunyoujun.cn
  #   title: 云游君的赞助者们
  # beian:
  #   enable: true
  #   icp: 苏ICP备17038157号
  # support:
  #   enable: true
  #   title: 又拍云
  #   link: https://www.upyun.com
  #   logo: https://cdn.yunyoujun.cn/img/logo/upyun-logo.png
  #   prefix: 本网站由
  #   suffix: 提供 CDN 加速
  custom_text: ''
  
  live_time:
    enable: true
    prefix: 本博客已运行
    suffix: (●'◡'●)
    start_time: "2025-08-14T00:00:00"
  

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
# algolia_search:
#   enable: true
  # ...

google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: false

tags:
  动画: crimson
  漫画: orange
  Parcel: '#21374b'
  学习: saddlebrown
  MAD: crimson
  教程: royalblue
  笔记: dimgray
  分享: '#0078e7'
  随笔: mediumpurple
  Blender: '#d04d2d'
  Linux: '#2577b1'
  中传: '#ccb44b'
  部落: '#DD306A'
  科幻: midnightblue
  蚂蚁森林: '#54a892'

# categories:
#   云游的小视频: '#FB7299'

# pages:
#   - name: 我的小伙伴们
#     url: /links/
#     icon: ri:genderless-line
#     color: dodgerblue
#   - name: 喜欢的女孩子
#     url: /girls/
#     icon: ri:women-line
#     color: hotpink

menu:
  custom:
    title: 留言板
    path: /about/#comment
    icon: ri:clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

# wordcount:
#   enable: true

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: true

social:
  # - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    # link: /atom.xml # config.feed.path
    # icon: ri:rss-line
    # color: orange
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: /images/qq-qrcode.jpg
    icon: ri:qq-line
    color: '#12B7F5'
  - name: GitHub
    link: https://github.com/NanCheng112
    icon: ri:github-line
    color: '#6e5494'
  # - name: 微博
  #   link: https://weibo.com/jizhideyunyoujun
  #   icon: ri:weibo-line
  #   color: '#E6162D'
  # - name: 豆瓣
  #   link: https://www.douban.com/people/yunyoujun/
  #   icon: ri:douban-line
  #   color: '#007722'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=1530621578
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  # - name: 知乎
  #   link: https://www.zhihu.com/people/yunyoujun/
  #   icon: ri:zhihu-line
  #   color: '#0084FF'
  - name: 哔哩哔哩
    link: https://space.bilibili.com/1207874912?spm_id_from=333.788.0.0
    icon: ri:bilibili-line
    color: '#FF8EB3'
  # - name: 微信公众号
  #   link: https://cdn.yunyoujun.cn/img/about/white-qrcode-and-search.jpg
  #   icon: ri:wechat-2-line
  #   color: '#1AAD19'
  - name: X
    link: https://x.com/LonjinoMar
    icon: ri:twitter-x-line
    color: '#1da1f2'
  # - name: Telegram
  #   link: https://t.me/yunyoujun_group
  #   icon: ri:telegram-line
  #   color: "#0088CC"
  # - name: Telegram Channel
  #   link: https://t.me/elpsycn
  #   # icon: ri:telegram-fill
  #   icon: ri:telegram-line
  #   color: '#0088CC'
  # - name: Discord
  #   link: https://discord.gg/nd3mPkU5j8
  #   icon: ri:discord-line
  #   color: '#5A6DE2'
  - name: E-Mail
    link: mailto:nanchengbei@foxmail.com
    icon: ri:mail-line
    color: '#8E71C1'
  # - name: Travelling
  #   link: https://travellings.link
  #   icon: ri:train-line
  #   color: black
# pjax:
#   enable: true